### ISSUE TITLE
s3導入で server error

### ISSUE THREAD

**Issue by ma96o** [masaaki1915/chatspace#25]
submit後のエラー文

``` Started POST "/groups/34/messages.json" for ::1 at 2017-03-26 15:23:42 +0900
Processing by MessagesController#create as JSON
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"3cx60ya7VibrkM9gMe7aOc4mMP06B36O6890JKEJYie1zbvgnL1+6TXbG/cW/vHJfXYgBpA+gzTISpH83KuWQA==", "message"=>{"text"=>"", "image"=>#<ActionDispatch::Http::UploadedFile:0x007f83720e9118 @tempfile=#<Tempfile:/var/folders/jj/t9sn5cld2vz3dnb2k1j_pwj80000gn/T/RackMultipart20170326-9215-jrayge.jpg>, @original_filename="plofile_fb_n.jpg", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"message[image]\"; filename=\"plofile_fb_n.jpg\"\r\nContent-Type: image/jpeg\r\n">}, "group_id"=>"34"}
  User Load (0.3ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 4 ORDER BY `users`.`id` ASC LIMIT 1
  Group Load (0.3ms)  SELECT  `groups`.* FROM `groups` WHERE `groups`.`id` = 34 LIMIT 1
   (0.1ms)  BEGIN
  SQL (0.3ms)  INSERT INTO `messages` (`user_id`, `group_id`, `text`, `image`, `created_at`, `updated_at`) VALUES (4, 34, '', 'plofile_fb_n.jpg', '2017-03-26 06:23:42', '2017-03-26 06:23:42')
   (12.4ms)  ROLLBACK
Completed 500 Internal Server Error in 25ms (ActiveRecord: 13.5ms)
  
  
  
  
ArgumentError ( is not a recognized provider):

app/controllers/messages_controller.rb:10:in `create'
  Rendering /Users/kubo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/templates/rescues/diagnostics.text.erb
  Rendering /Users/kubo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/templates/rescues/_source.text.erb
  Rendered /Users/kubo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/templates/rescues/_source.text.erb (1.0ms)
  Rendering /Users/kubo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/templates/rescues/_trace.text.erb
  Rendered /Users/kubo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/templates/rescues/_trace.text.erb (1.3ms)
  Rendering /Users/kubo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/templates/rescues/_request_and_response.text.erb
  Rendered /Users/kubo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/templates/rescues/_request_and_response.text.erb (1.6ms)
  Rendered /Users/kubo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/templates/rescues/diagnostics.text.erb (69.4ms) ```

**Comment by ma96o** [comment]
config/initializers/carrierwave.rb

```ruby:carrerxave.rb
require 'carrierwave/storage/abstract'
require 'carrierwave/storage/file'
require 'carrierwave/storage/fog'

CarrierWave.configure do |config|
  case Rails.env
    when 'production' || 'development'
      config.storage = :fog
      config.fog_provider = 'fog/aws'
      config.fog_credentials = {
        provider: 'AWS',
        aws_access_key_id: ENV['S3_ACCESS_KEY_ID'],
        aws_secret_access_key: ENV['S3_SECRET_ACCESS_KEY'],
        region: 'ap-northeast-1'
      }
      config.fog_directory = 'chat-space-images-mk'
      config.asset_host = 'https://s3-ap-northeast-1.amazonaws.com/chat-space-images-mk'
    when 'test'
      config.storage = :file
  end
end
```

**Comment by ma96o** [comment]
app/uploaders/image_uploader.rb(コメントアウト省略)

```ruby:image_uploader.rb
class ImageUploader < CarrierWave::Uploader::Base

  storage :fog

  def store_dir
    "uploads/#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}"
  end

end
```

**Comment by ma96o** [comment]
ちなみに最初以下のようにエラーが出て、最下行は`gem'web-console'`のバージョンを上げたらwarnig消えました

```
ArgumentError ( is not a recognized provider):

app/controllers/messages_controller.rb:10:in `create'
  Rendering /Users/kubo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/templates/rescues/diagnostics.text.erb
  Rendering /Users/kubo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/templates/rescues/_source.text.erb
  Rendered /Users/kubo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/templates/rescues/_source.text.erb (0.9ms)
  Rendering /Users/kubo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/templates/rescues/_trace.text.erb
  Rendered /Users/kubo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/templates/rescues/_trace.text.erb (1.1ms)
  Rendering /Users/kubo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/templates/rescues/_request_and_response.text.erb
  Rendered /Users/kubo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/templates/rescues/_request_and_response.text.erb (1.2ms)
  Rendered /Users/kubo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/templates/rescues/diagnostics.text.erb (73.8ms)
DEPRECATION WARNING: Accessing mime types via constants is deprecated. Please change `Mime::HTML` to `Mime[:html]`. (called from acceptable_content_type? at /Users/kubo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/web-console-2.3.0/lib/web_console/middleware.rb:58)
```

**Comment by ma96o** [comment]
awsの設定とかのが怪しいっすかね、

**Comment by sato11** [comment]
```
ArgumentError ( is not a recognized provider):
```
とあるけど、 is の前が空白になっている == provider: 'AWS' が読まれていない
ということが成り立つよね。

すると carrierwave.rb が読まれていないか、 case 文が機能していないかとかじゃないかなあ。
いずれにせよ carrierwave.rb に問題がある気がする。

設定する時に参考にしたサイトってある？

**Comment by ma96o** [comment]
佐藤さんありがとうございました！！


### 解決後のメモ

原因 => case文の文法ミス

解決に至った思索フロー=>
config.~あたりどんだけ変えてもあかん→caseとってみたら違うエラー →それ解決→caseつけたらまた最初のエラー →pryでcase文確認→あかん→caseの文法ミスってるやん

最適な思索フロー=>
> ```
> ArgumentError ( is not a recognized provider):
> ```
> とあるけど、 is の前が空白になっている == provider: 'AWS' が読まれていない
> ということが成り立つよね。
>
> すると carrierwave.rb が読まれていないか、 case 文が機能していないかとかじゃないかなあ。

試したこと=>新しいバケット作成（regionの変更）、IAMユーザの変更、環境変数を再定義など、、

かけた時間=>5時間ちょい
